[project]
name = "oibot"
version = "2026.2.25"
description = "a lightweight bot framework"
readme = "README.md"
requires-python = ">=3"
dependencies = [
    "aiohttp",
    "cryptography",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
